version: '3.4'

services:

  wordpress:
    build: .
    # image: wordpress
    restart: always
    ports:
      - ${DEV_PORT}:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: pass
      WORDPRESS_DB_NAME: db
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME','${DEV_HOST}');
        define('WP_SITEURL','${DEV_HOST}');
    volumes:
      - ./workspace/wordpress:/var/www/html

  db:
    image: mysql:8
    restart: always
    logging:
      driver: none
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./workspace/db:/var/lib/mysql

# volumes:
#   wordpress:
#   db:
