version: '3.4'

services:

  wordpress:
    build: .
    restart: always
    ports:
      - ${DEV_PORT}:80
    env_file:
      - dev.env
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME','${DEV_HOST}');
        define('WP_SITEURL','${DEV_HOST}');
    volumes:
      - ./workspace/wordpress:/var/www/html

  mysql:
    image: mysql:8
    restart: always
    logging:
      driver: none
    env_file:
      - dev.env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./workspace/db:/var/lib/mysql

# volumes:
#   wordpress:
#   db:
